// Generated by `wit-bindgen` 0.49.0. DO NOT EDIT!
#include "main.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `betty-blocks:nth-prime-number/nth-prime-number`

__attribute__((__weak__, __export_name__("cabi_post_betty-blocks:nth-prime-number/nth-prime-number#calculate")))
void __wasm_export_exports_betty_blocks_nth_prime_number_nth_prime_number_calculate_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(3*sizeof(void*))];

// Helper Functions

void exports_betty_blocks_nth_prime_number_nth_prime_number_result_u32_string_free(exports_betty_blocks_nth_prime_number_nth_prime_number_result_u32_string_t *ptr) {
  if (!ptr->is_err) {
  } else {
    main_string_free(&ptr->val.err);
  }
}

void main_string_set(main_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void main_string_dup(main_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void main_string_free(main_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__export_name__("betty-blocks:nth-prime-number/nth-prime-number#calculate")))
uint8_t * __wasm_export_exports_betty_blocks_nth_prime_number_nth_prime_number_calculate(int32_t arg) {
  exports_betty_blocks_nth_prime_number_nth_prime_number_result_u32_string_t ret;
  uint32_t ok;
  main_string_t err;
  ret.is_err = !exports_betty_blocks_nth_prime_number_nth_prime_number_calculate((uint16_t) (arg), &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const main_string_t *payload0 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload0).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload0).ptr;
  } else {
    const uint32_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int32_t*)(ptr + sizeof(void*))) = (int32_t) (*payload);
  }
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_main(void);
__attribute__((used))
void __component_type_object_force_link_main_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_main();
}
