// Generated by `wit-bindgen` 0.49.0. DO NOT EDIT!
#ifndef __BINDINGS_MAIN_H
#define __BINDINGS_MAIN_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct main_string_t {
  uint8_t*ptr;
  size_t len;
} main_string_t;

// Exported Functions from `betty-blocks:concat-text/concat-text`
void exports_betty_blocks_concat_text_concat_text_concat(main_string_t *a, main_string_t *b, main_string_t *ret);

// Helper Functions

// Sets the string `ret` to reference the input string `s` without copying it
void main_string_set(main_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void main_string_dup(main_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void main_string_free(main_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
