// Generated by `wit-bindgen` 0.49.0. DO NOT EDIT!
#include "main.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `betty-blocks:concat-text/concat-text`

__attribute__((__weak__, __export_name__("cabi_post_betty-blocks:concat-text/concat-text#concat")))
void __wasm_export_exports_betty_blocks_concat_text_concat_text_concat_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(2*sizeof(void*))];

// Helper Functions

void main_string_set(main_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void main_string_dup(main_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void main_string_free(main_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__export_name__("betty-blocks:concat-text/concat-text#concat")))
uint8_t * __wasm_export_exports_betty_blocks_concat_text_concat_text_concat(uint8_t * arg, size_t arg0, uint8_t * arg1, size_t arg2) {
  main_string_t arg3 = (main_string_t) { (uint8_t*)(arg), (arg0) };
  main_string_t arg4 = (main_string_t) { (uint8_t*)(arg1), (arg2) };
  main_string_t ret;
  exports_betty_blocks_concat_text_concat_text_concat(&arg3, &arg4, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_main(void);
__attribute__((used))
void __component_type_object_force_link_main_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_main();
}
