// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
#ifndef __BINDINGS_MAIN_H
#define __BINDINGS_MAIN_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct main_string_t {
  uint8_t*ptr;
  size_t len;
} main_string_t;

typedef struct {
  bool is_err;
  union {
    uint32_t ok;
    main_string_t err;
  } val;
} exports_betty_blocks_nth_prime_number_nth_prime_number_result_u32_string_t;

// Exported Functions from `betty-blocks:nth-prime-number/nth-prime-number`
bool exports_betty_blocks_nth_prime_number_nth_prime_number_calculate(uint16_t n, uint32_t *ret, main_string_t *err);

// Helper Functions

void exports_betty_blocks_nth_prime_number_nth_prime_number_result_u32_string_free(exports_betty_blocks_nth_prime_number_nth_prime_number_result_u32_string_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void main_string_set(main_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void main_string_dup(main_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void main_string_dup_n(main_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void main_string_free(main_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
