[package]
name = "http-request"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.140"
url = "2.5.4"
waki = "0.5.1"
wasi = "0.14.2"
wit-bindgen = "0.42.0"
