// Generated by `wit-bindgen` 0.49.0. DO NOT EDIT!
#ifndef __BINDINGS_MAIN_H
#define __BINDINGS_MAIN_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Exported Functions from `betty-blocks:calculator/calculator`
double exports_betty_blocks_calculator_calculator_add(double a, double b);
double exports_betty_blocks_calculator_calculator_subtract(double a, double b);
double exports_betty_blocks_calculator_calculator_multiply(double a, double b);
double exports_betty_blocks_calculator_calculator_divide(double a, double b);

#ifdef __cplusplus
}
#endif
#endif
