// Generated by `wit-bindgen` 0.49.0. DO NOT EDIT!
#include "main.h"
#include <stdlib.h>

// Exported Functions from `betty-blocks:calculator/calculator`





// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Component Adapters

__attribute__((__export_name__("betty-blocks:calculator/calculator#add")))
double __wasm_export_exports_betty_blocks_calculator_calculator_add(double arg, double arg0) {
  double ret = exports_betty_blocks_calculator_calculator_add(arg, arg0);
  return ret;
}

__attribute__((__export_name__("betty-blocks:calculator/calculator#subtract")))
double __wasm_export_exports_betty_blocks_calculator_calculator_subtract(double arg, double arg0) {
  double ret = exports_betty_blocks_calculator_calculator_subtract(arg, arg0);
  return ret;
}

__attribute__((__export_name__("betty-blocks:calculator/calculator#multiply")))
double __wasm_export_exports_betty_blocks_calculator_calculator_multiply(double arg, double arg0) {
  double ret = exports_betty_blocks_calculator_calculator_multiply(arg, arg0);
  return ret;
}

__attribute__((__export_name__("betty-blocks:calculator/calculator#divide")))
double __wasm_export_exports_betty_blocks_calculator_calculator_divide(double arg, double arg0) {
  double ret = exports_betty_blocks_calculator_calculator_divide(arg, arg0);
  return ret;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_main(void);
__attribute__((used))
void __component_type_object_force_link_main_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_main();
}
